# Generated by Django 5.2.14 on 2026-05-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyentry',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_entry', to='domains.domain'),
        ),
    ]
