# Generated by Django 5.2.14 on 2026-05-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_alter_proxyentry_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='deploy_path',
            field=models.CharField(blank=True, help_text='Where to copy issued certificates. Overrides the global certbot.deploy_path. Relative paths are based on the home/ directory.', max_length=512),
        ),
    ]
