# Generated by Django 5.2.14 on 2026-05-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_domain_deploy_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='deploy_path',
            field=models.CharField(blank=True, help_text='Where to copy issued certificates. Overrides the global certbot.deploy_path. Relative paths are resolved against the config.yaml directory.', max_length=512),
        ),
    ]
