# Generated by Django 5.2.14 on 2026-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_proxyentry_home_host'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proxyentry',
            constraint=models.UniqueConstraint(fields=('home_host', 'home_port'), name='unique_home_host_port'),
        ),
    ]
