# Generated by Django 5.2.14 on 2026-06-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_tcp_proxy_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxyentry',
            name='cloudserver_host',
        ),
    ]
