# Generated by Django 5.2.16 on 2026-07-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_remove_cloudserver_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyentry',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxy_entries', to='domains.domain'),
        ),
        migrations.AddConstraint(
            model_name='proxyentry',
            constraint=models.UniqueConstraint(fields=('domain', 'scheme'), name='unique_domain_scheme'),
        ),
    ]
