# Generated by Django 5.2.16 on 2026-09-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_proxyentry_multiple_schemes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proxyentry',
            name='unique_domain_scheme',
        ),
        migrations.AddConstraint(
            model_name='proxyentry',
            constraint=models.UniqueConstraint(fields=('domain', 'scheme', 'public_port'), name='unique_domain_scheme_port'),
        ),
    ]
