# Generated by Django 5.2.16 on 2026-09-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0010_proxyentry_multiple_ports_per_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyentry',
            name='tunnel_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
