cloudserver_url: http://localhost:8000
auth_token: 8d8187efdd76094d613a500aa9fe688bdf5125ef
home_slug: UxSa_K8zxk64j7ZFcMc3dQ
ssh:
  host: localhost
  port: 8022
  username: home01_maria
  private_key_path: /home/nando/.ssh/cloudathome_ed25519
ports:
  base: 2100
  count: 10
